// Re-export every table from this barrel so drizzle-kit and the db client see it.
// auth.ts is generated by `pnpm auth:generate`; don't edit it by hand.
export * from "./auth";
export * from "./catalog";
